/**
 * /training/fast-start/comp-layer-1 — Module 2: Comp Plan, Layer 1.
 *
 * Source: Team Magnificent's published "Power in Numbers" comp training
 * (devklg/team-magnificent-training/index.html), Kevin-authorized in
 * TASK.md ("upline-sanctioned, adapt freely"). This module ports the
 * 6-ways + cycle mechanic + Active/Qualified + the activation path
 * INTO the Fast Start flow.
 *
 * The TEACHING MANDATE from TASK.md (this is the JOB):
 *   THREE tracks all volume in its own back office. This app NEVER
 *   computes CV. The training's job is purely CONCEPTUAL — teach the
 *   BA three things, in this order:
 *     1. What CV is and where it comes from (organization-wide).
 *     2. How volume becomes a check (300+600 = 900 = $35 cycle).
 *     3. Active + Qualified to earn (so the math even applies).
 *
 * Module 3 covers the exponential / no-breakage / first-mover —
 * the structural reasons the duplication is REALIZABLE not fantastical.
 * Keep that out of here; this module is the foundation.
 *
 * Compliance scope: .team only. CV/dollar figures are legitimate
 * inside this regulated training environment and never bleed to .com.
 */

import {
  ModuleScaffold,
  SectionLabel,
  SectionTitle,
  Prose,
  Callout,
  DataCard,
} from './_scaffold';

export function ModuleCompLayer1Page() {
  return (
    <ModuleScaffold moduleId={2}>
      {/* ── What CV is ──────────────────────────────────────────── */}
      <SectionLabel>The unit of the system</SectionLabel>
      <SectionTitle>CV is Commissionable Volume.</SectionTitle>
      <Prose>
        <p>
          Every product in the THREE catalog has a CV number attached to it. CV is generated by{' '}
          <strong className="text-cream">every order from every person</strong> — Brand Ambassador or
          customer — anywhere in your organization, on either leg, at any depth. You do not
          personally generate thousands of CV. Your organization does it collectively, every order,
          every month.
        </p>
        <p>
          THREE tracks every CV figure in their back office. This app never computes a single one.
          What you need to know is just enough to read your back office and understand what your team
          is doing for you.
        </p>
      </Prose>

      {/* ── The 6 ways ──────────────────────────────────────────── */}
      <SectionLabel>The big picture</SectionLabel>
      <SectionTitle>Six ways a Brand Ambassador gets paid.</SectionTitle>
      <Prose>
        <p>
          THREE pays six different ways. Five of them are bonuses, accelerators, and overrides on top
          of the engine. The engine itself is <strong className="text-cream">Team Commissions</strong>{' '}
          — the cycle structure. Everything else multiplies what your team's volume produces.
        </p>
      </Prose>

      <div className="border-l-4 border-gold bg-[#1A1A1A] my-6 divide-y divide-line">
        <PayWayRow n="01" name="Customer Retail Commissions" pct="25%" />
        <PayWayRow n="02" name="Product Introduction Bonus (PIB)" pct="enrollment pack" />
        <PayWayRow n="03" name="★ Team Commissions (Cycles)" pct="THE ENGINE" highlight />
        <PayWayRow n="04" name="Leadership Matching Bonuses" pct="upline match" />
        <PayWayRow n="05" name="Performance Bonuses" pct="rank-based" />
        <PayWayRow n="06" name="Global Leadership Bonus Pool" pct="top-rank pool" />
      </div>

      <Prose>
        <p>
          Module 2 is about #3 — Team Commissions — because that is the structure the rest of this
          training depends on. The other five lift the ceiling; this one builds the floor.
        </p>
      </Prose>

      {/* ── How volume becomes a check ──────────────────────────── */}
      <SectionLabel>How volume becomes a check</SectionLabel>
      <SectionTitle>The cycle: 300 + 600 = 900 = $35.</SectionTitle>
      <Prose>
        <p>
          A cycle is the unit of pay. When <strong className="text-cream">300 CV</strong> accumulates
          on your lesser leg and <strong className="text-cream">600 CV</strong> on your greater leg —
          900 CV total — one cycle fires. One cycle = $35, paid weekly. Either leg can be the lesser
          or the greater; it works both directions. The ratio is always 1:2.
        </p>
        <p>
          Unused volume <strong className="text-cream">carries forward</strong> to the next week.
          Nothing is lost. You stack toward your next cycle, week after week, as your team's orders
          come in.
        </p>
      </Prose>

      <div className="grid grid-cols-3 gap-2 my-8">
        <DataCard num="900" label="CV per cycle" />
        <DataCard num="$35" label="Paid per cycle" highlight />
        <DataCard num="600" label="Max cycles per week" />
      </div>

      <Callout tone="gold" title="THE WEEKLY CEILING">
        Base cap is <strong className="text-cream">500 cycles per week</strong>, expandable to{' '}
        <strong className="text-cream">600 cycles</strong> when rank and volume qualifications are
        met. 600 × $35 = $21,000 per week maximum. The ceiling is real — but the math that gets you
        anywhere near it is in Module 3.
      </Callout>

      {/* ── Active + Qualified ──────────────────────────────────── */}
      <SectionLabel>The gate to earn</SectionLabel>
      <SectionTitle>Active + Qualified.</SectionTitle>
      <Prose>
        <p>
          The cycle math only applies if you meet two requirements during the commission period. Miss
          either one, and your team can be stacking volume but the payouts skip you. Both are simple,
          both are designed to be sustainable, and both are non-negotiable.
        </p>
      </Prose>

      <div className="grid md:grid-cols-2 gap-3 my-6">
        <RequirementCard
          title="ACTIVE"
          line1="100 CV"
          line1Label="initial purchase at enrollment"
          line2="60 CV"
          line2Label="every 28 days (SmartShip)"
          body="SmartShip on a 60 CV / 28-day cadence is 'the glue.' Set and forget. Earn $100 of free product every 6 months you stay active ($200/year) + 10% loyalty savings."
        />
        <RequirementCard
          title="QUALIFIED"
          line1="1 BA"
          line1Label="personally sponsored, LEFT leg"
          line2="1 BA"
          line2Label="personally sponsored, RIGHT leg"
          body="One on each side. This is the activation step, NOT the income model — your first two unlock your ability to earn. Then the real work (Module 5) begins."
        />
      </div>

      <Callout tone="teal" title="THE QBA PATH IN ORDER">
        Enroll ($30/yr) → initial order at <strong className="text-cream">100 CV minimum</strong>{' '}
        (100 activates; 60 does NOT) → set SmartShip at{' '}
        <strong className="text-cream">60 CV / 28 days</strong> → enroll one BA left + one BA right.
        All four done = <strong className="text-cream">Qualified Brand Ambassador</strong>. The
        earning door opens.
      </Callout>

      {/* ── Quick cash levers (PIBs + 2-by-2) ───────────────────── */}
      <SectionLabel>Quick cash levers</SectionLabel>
      <SectionTitle>While the team is stacking — PIBs + 2-by-2.</SectionTitle>
      <Prose>
        <p>
          The cycle engine takes a beat to spin up. While your team's volume is stacking on the legs,
          THREE pays two immediate bonuses you can earn from week one. Both are real, both are
          uncapped per qualified enrollment, and both compound with the cycle structure — they don't
          replace it.
        </p>
      </Prose>

      <div className="border border-line bg-[#1A1A1A] my-6">
        <BonusRow
          label="Essential Pack"
          amount="$25"
          note="GLP-THREE Essential / similar starter — fast cash + the volume sits in the tree to cycle on"
        />
        <BonusRow label="Starter Pack" amount="$50" note="Simple Six Starter — 200 CV in the tree" />
        <BonusRow label="Boost Pack" amount="$75" note="Simple Six Boost — 350 CV in the tree" />
        <BonusRow
          label="Advantage / Complete Pack"
          amount="$100"
          note="GLP-THREE Advantage / Simple Six Elite — 300–500 CV in the tree"
        />
        <BonusRow
          label="Ultimate Pack"
          amount="$250"
          note="Simple Six Ultimate — 900 CV in the tree (a full cycle by itself)"
          last
        />
      </div>

      <Prose>
        <p>
          <strong className="text-cream">2-by-2 bonus.</strong> When you help someone you sponsored
          get their two, you earn $25. At the next level it's $50 each. This is the bonus designed to
          make you the upline who actually helps — because you don't earn it by leaving them alone.
        </p>
      </Prose>

      {/* ── The closing belief ──────────────────────────────────── */}
      <SectionLabel>What you need to walk away believing</SectionLabel>
      <SectionTitle>You don't compute. You teach.</SectionTitle>
      <Prose>
        <p>
          The actual numbers are in THREE's back office, and they change as the company tunes things.
          The job of this module is not to memorize every dollar figure. It's to internalize the
          shape: <strong className="text-cream">CV comes from the whole org. Cycles convert volume
          to checks. Active + Qualified to earn.</strong> Everything else — what the rest of this
          Fast Start teaches — is how to get the cycle engine spinning and keep it spinning.
        </p>
        <p className="text-gold font-display tracking-[0.06em] text-[18px] mt-6">
          Module 3 is where the duplication math gets real. You'll see why "find your two" is the
          activation step — and what the actual income model looks like.
        </p>
      </Prose>
    </ModuleScaffold>
  );
}

function PayWayRow({
  n,
  name,
  pct,
  highlight,
}: {
  n: string;
  name: string;
  pct: string;
  highlight?: boolean;
}) {
  return (
    <div
      className={`grid grid-cols-[40px_1fr_auto] gap-4 items-center p-4 ${highlight ? 'bg-gold/[0.08]' : ''}`}
    >
      <div className="font-mono text-[11px] text-gold/60 tracking-[0.1em]">{n}</div>
      <div className={`font-display tracking-[0.04em] text-[16px] ${highlight ? 'text-gold' : 'text-cream'}`}>
        {name}
      </div>
      <div className="font-mono tracking-[0.15em] text-[10px] text-cream-mute uppercase">{pct}</div>
    </div>
  );
}

function RequirementCard({
  title,
  line1,
  line1Label,
  line2,
  line2Label,
  body,
}: {
  title: string;
  line1: string;
  line1Label: string;
  line2: string;
  line2Label: string;
  body: string;
}) {
  return (
    <div className="bg-[#1A1A1A] border-l-4 border-gold p-5">
      <div className="font-mono tracking-[0.25em] text-[11px] text-gold uppercase mb-4">{title}</div>
      <div className="space-y-3 mb-4">
        <div>
          <div className="font-display text-[24px] text-cream leading-none">{line1}</div>
          <div className="font-mono tracking-[0.1em] text-[10px] text-cream-mute uppercase mt-1">
            {line1Label}
          </div>
        </div>
        <div className="font-mono text-[10px] text-cream-faint">+</div>
        <div>
          <div className="font-display text-[24px] text-cream leading-none">{line2}</div>
          <div className="font-mono tracking-[0.1em] text-[10px] text-cream-mute uppercase mt-1">
            {line2Label}
          </div>
        </div>
      </div>
      <div className="text-cream-mute text-[13px] leading-[1.6] font-light border-t border-line pt-3">
        {body}
      </div>
    </div>
  );
}

function BonusRow({
  label,
  amount,
  note,
  last,
}: {
  label: string;
  amount: string;
  note: string;
  last?: boolean;
}) {
  return (
    <div
      className={`grid grid-cols-[1fr_auto] gap-4 items-center p-4 ${last ? '' : 'border-b border-line'}`}
    >
      <div>
        <div className="font-display tracking-[0.04em] text-[15px] text-cream">{label}</div>
        <div className="text-cream-mute text-[12px] leading-[1.5] font-light mt-1">{note}</div>
      </div>
      <div className="font-display text-[24px] text-gold leading-none">{amount}</div>
    </div>
  );
}
