export const MCS_EVENT_CENTER_CATALOG = {
  surface: 'event_center',
  productBoundary: 'named_event_discovery_and_coordination_surface_over_source_owned_events',
  currentState: 'attendance_to_human_crm_live',
  teamRoute: '/events',
  adminRoute: '/events',
  access: {
    team: 'ba_authenticated',
    admin: 'founder_admin',
    prospect: 'event_specific_token_flow_only',
  },
  sourceDomains: [
    {
      domain: 'new_member_orientation',
      owner: 'orientation',
      audience: ['brand_ambassador', 'founder_admin'],
      sourceCollections: ['tmag_new_member_orientation_sessions', 'tmag_new_member_orientation_reservations'],
      currentApiRoutes: ['/api/orientation/sessions', '/api/admin/orientation/sessions'],
      eventCenterApiRoutes: ['/api/events', '/api/admin/events', '/api/admin/events/webinars/:eventId/reservations/:reservationId/attendance'],
      currentAdminRoute: '/orientation',
    },
    {
      domain: 'prospect_webinars',
      owner: 'prospect_webinar',
      audience: ['prospect', 'brand_ambassador', 'founder_admin'],
      sourceCollections: ['tmag_prospect_webinar_events', 'tmag_prospect_webinar_reservations'],
      currentApiRoutes: ['/api/p/:token/webinar-reserve'],
      eventCenterApiRoutes: ['/api/events', '/api/admin/events'],
      prospectAccess: 'valid_invitation_token_only',
    },
    {
      domain: 'event_materials',
      owner: 'resource_center_source_owner',
      audience: ['brand_ambassador', 'leader'],
      sourceCollections: ['tmag_resource_catalog'],
      inclusion: 'verified_resource_with_explicit_event_context_tag_only',
      inference: 'forbidden',
    },
  ],
  ownership: {
    eventCenter: ['discovery', 'calendar_composition', 'event_type_filtering', 'source_owner_deep_link', 'explicit_webinar_attendance_capture'],
    sourceDomains: ['event_authority', 'scheduling', 'capacity', 'reservation', 'attendance', 'materials', 'follow_up'],
    admin: ['event_operations', 'visibility', 'host_assignment', 'rosters'],
  },
  lifecycleRules: {
    reservationDoesNotProveAttendance: true,
    elapsedTimeDoesNotProveAttendance: true,
    eventCenterDoesNotChangeTokenLifecycle: true,
    sponsorIdentityRemainsTokenDerived: true,
    crmFollowUpRemainsHumanOwned: true,
    attendanceRequiresExplicitAdminAction: true,
    attendanceCreatesNoAutomatedContact: true,
    existingCrmReminderIsPreserved: true,
  },
  normalizedModel: {
    schemaVersion: 'event_center.v1.2',
    fields: ['eventType', 'visibility', 'capacity', 'registration', 'reminders', 'attendance', 'followUp'],
    persistence: 'source_owned_attendance_plus_read_projection',
    acr: 'ACR-0016',
  },
  exclusions: [
    'new_event_authority',
    'automatic_attendance_inference',
    'automatic_prospect_follow_up',
    'public_event_directory',
    'training_sequence_or_completion',
    'resource_approval_or_publishing',
    'three_way_call_booking',
    'broadcast_composer',
    'duplicate_orientation_or_webinar_records',
  ],
  deferred: {},
} as const;
