export const MCS_RESOURCE_CENTER_CATALOG = {
  surface: 'resource_center',
  productBoundary: 'named_ba_library_over_source_owned_resources',
  currentState: 'named_ui_live_version_safe_projection',
  teamRoute: '/resources',
  access: 'ba_authenticated',
  primaryAudience: ['brand_ambassador', 'leader'] as const,
  ownerAudience: ['founder_admin'] as const,
  sourceDomains: [
    {
      domain: 'content_videos',
      owner: 'product_gallery',
      currentTeamRoute: '/video-library',
      currentAdminRoute: '/content-videos',
      apiRoute: '/api/content/videos',
      sourceCollections: ['tmag_content_videos', 'mcs_content_videos'],
      inclusion: 'catalog_projection_required',
      versionSafety: 'legacy_active_boolean_is_not_catalog_activation',
      aliases: ['video_library', 'product_gallery'],
    },
    {
      domain: 'training_content',
      owner: 'training',
      currentTeamRoutes: ['/training/fast-start', '/training/10-steps'],
      sourceLocations: [
        'apps/team/src/routes/training/fast-start',
        'apps/team/src/routes/training/10-steps.tsx',
      ],
      inclusion: 'catalog_projection_required',
      versionSafety: 'code_owned_content_requires_version_and_digest_projection',
      resourceConnection: 'explicit_context_tag_only',
    },
    {
      domain: 'approved_knowledge',
      owner: 'knowledge_core',
      currentAdminRoute: '/knowledge',
      apiRoute: '/api/admin/knowledge',
      sourceCollections: ['mcs_knowledge_sources', 'mcs_knowledge_chunks'],
      inclusion: 'active_human_approved_human_readable_projection_only',
      versionSafety: 'source_authority_and_retrieval_eligibility_remain_required',
    },
    {
      domain: 'event_materials',
      owner: 'event_center',
      currentState: 'approved_resources_linkable_to_orientation_and_webinar_contexts',
      inclusion: 'explicit_context_tag_only',
      versionSafety: 'event_schedules_and_reservations_are_not_resources',
    },
  ],
  versionSafety: {
    schema: 'resource_catalog.v1',
    mongoCollection: 'tmag_resource_catalog',
    neo4jLabels: ['TmagResource', 'TmagResourceVersion'],
    chromaCollection: 'mcs_resource_catalog',
    retrievalLifecycle: 'active',
    publishingRule: 'exact_mongo_neo4j_chroma_identity_version_digest_and_freshness',
    sourceRule: 'catalog_is_projection_not_source_authority',
  },
  ownership: {
    resourceCenter: ['discovery', 'browse', 'search', 'filter', 'source_owner_deep_link'],
    sourceDomains: ['authoring', 'content_accuracy', 'workflow_state', 'source_records'],
    admin: ['approval', 'audience', 'lifecycle', 'readiness', 'retirement'],
  },
  connections: {
    authority: 'kevin_selected_during_knowledge_approval',
    inference: 'forbidden',
    trainingTagPrefix: 'context:training:',
    eventTagPrefix: 'context:event:',
    graphRelationships: ['SUPPORTS_TRAINING_MODULE', 'SUPPORTS_EVENT_MATERIAL'],
    consumers: ['fast_start_modules', 'ten_step_orientation', 'orientation_event_card'],
  },
  exclusions: [
    'prospect_public_surface',
    'training_sequence_or_progress',
    'event_scheduling_registration_or_attendance',
    'candidate_unapproved_or_private_knowledge',
    'raw_admin_authoring_workflows',
    'crm_records',
    'semantic_similarity_as_truth',
    'duplicate_content_authority',
  ],
  deferred: {
    p2_102: ['usage_analytics', 'stale_resource_warnings'],
  },
} as const;
